# Generated by Django 6.0.3 on 2026-04-12 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('nome', models.CharField(max_length=180)),
                ('capa_url', models.URLField(blank=True, default='')),
                ('plataforma', models.CharField(blank=True, default='', max_length=220)),
                ('slug', models.SlugField(blank=True, default='', max_length=220)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='JogoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('vou_jogar', 'Vou Jogar'), ('to_jogando', 'Tô jogando'), ('ja_zerei', 'Já Zerei'), ('desisti', 'Desisti')], default='vou_jogar', max_length=20)),
                ('horas_jogadas', models.PositiveIntegerField(default=0)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='jogos.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'jogo'), name='jogo_unico_por_usuario')],
            },
        ),
    ]
